[package]
name = "hide"
version = "0.1.0"
edition = "2021"

[dependencies]
bardecoder = "0.5.0"
flume = "0.11.0"
image = "0.25.2"
qrcode = "0.14.1"
quircs = "0.10.2"
rxing = "0.6.1"
threadpool = "1.8.1"
